### ISSUE TITLE
Bind vs. symlink

### ISSUE THREAD

**Issue by timsueberkrueb** [diddlesnaps/snapcraft-alsa#10]
Hey, thanks for this very useful snapcraft part!

The [layout docs](https://snapcraft.io/docs/snap-layouts) recommend using `symlink` over `bind` where possible for performance reasons. Is there a specific reason for using `bind` for this alsa part? 

https://github.com/diddlesnaps/snapcraft-alsa/blob/edde1b15030ffc13efce46f03f929a336e214ea4/snapcraft.yaml#L29

In my testing with the `veloren` snap, using `symlink` seemed to work fine.

**Comment by lucyllewy** [comment]
I found that defining a layout with symlinks is more brittle and prone to failure.

**Comment by timsueberkrueb** [comment]
Okay, fair enough. Are there known problems with using `symlink` specifically with this ALSA part though?
As it seems to be working for veloren, I'm inclined to stick with using `symlink` over `bind` for veloren.

**Comment by lucyllewy** [comment]
I can't recall any specific to the alsa part, no

**Comment by timsueberkrueb** [comment]
Ok, thank you!
