### ISSUE TITLE
Fork me on GitHub button is pointing to the wrong url

### ISSUE THREAD

**Issue by guyluz11** [diddlesnaps/snapcraft-alsa#9]
In the [snapcraft-alsa-lib site](https://snapcraft-alsa.readthedocs.io/en/latest/snapcraft_usage.html) the `Fork me on GitHub` button in the upper right corner of the screen is redirecting to GitHub 404  ![image](https://user-images.githubusercontent.com/9304740/75280523-45b16580-5816-11ea-8270-4e7f89ef14d0.png)

**Comment by lucyllewy** [comment]
Thanks for spotting it and letting me know. This commit should fix it :-)
